version: 2

project_name: arpkit

builds:
  - id: arpkit
    main: ./cmd/arpkit
    binary: arpkit
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -buildid=
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}

archives:
  - id: tarball
    formats:
      - tar.gz
    builds_info:
      owner: root
      group: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: license*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: readme*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: README*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: changelog*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: CHANGELOG*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
  - id: zip
    formats:
      - zip
    builds_info:
      owner: root
      group: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: license*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: readme*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: README*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: changelog*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: CHANGELOG*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

checksum:
  name_template: checksums.txt

signs:
  - id: checksum
    artifacts: checksum
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args:
      - sign-blob
      - ${artifact}
      - --output-signature=${signature}
      - --output-certificate=${certificate}
      - --yes

sboms:
  - id: archives
    artifacts: archive
    documents:
      - "${artifact}.spdx.json"
    cmd: syft
    args:
      - ${artifact}
      - --output
      - spdx-json=${document}
      - --enrich
      - all

changelog:
  use: git

release:
  github:
    owner: pratik-anurag
    name: arpkit
